### ISSUE TITLE
Suggestion for further Software

### ISSUE THREAD

**Issue by Scabber** [roboterclubaachen/rca-vm#45]
Add the 3D Printer Software maybe?

**Comment by salkinium** [comment]
Hm, there is no 3D modelling software on the VM (especially not Solidworks), so why would you model the stuff in Windows, then use the VM to print it?

Maybe we want to connect the printer to our permanent PC in the room, so that it can run seperately.
Otherwise the person needs to have his/her computer with the VM running connected all the time the printer is running, which might suck a little.

**Comment by salkinium** [comment]
We should however, definitely check the printer settings into a repository, but perhaps not this one.
